[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "git-cp-pr"
dynamic = ["version"]
description = "Automated tool to cherry-pick commits and create PRs via GitHub CLI or markdown."
readme = "README.md"
authors = [{ name = "Jarosław Pelczar", email = "jarek@jpelczar.com" }]
license = { text = "The Unlicense" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: The Unlicense",
    "Operating System :: OS Independent",
]
requires-python = ">=3.6"
dependencies = []

[project.scripts]
git-cp-pr = "git_cp_pr:main"
git-cp-pr-gui = "git_cp_pr_gui:main"

[tool.setuptools]
py-modules = ["commit_tree", "git_cp_pr", "git_cp_pr_gui", "progressive_commit_loader"]

[tool.setuptools.data-files]
"share/git-cp-pr" = ["icon.png", "icon.ico"]
"share/git-cp-pr/locale/pl/LC_MESSAGES" = ["locale/pl/LC_MESSAGES/git_cp_pr_gui.po"]
"share/git-cp-pr/locale/ko/LC_MESSAGES" = ["locale/ko/LC_MESSAGES/git_cp_pr_gui.po"]

[tool.setuptools.dynamic]
version = { attr = "git_cp_pr.__version__" }
